### ISSUE TITLE
Majora's Mask Bombers Notebook is shaking/wobbling with filtered output mode

### ISSUE THREAD

**Issue by SigmaVirus** [ata4/angrylion-rdp-plus#27]
Seems like something have happened, although you can't see it on this static image this screen is actually shaking/wobbling like crazy on newer builds with filtered as selected output mode:

![pic01](https://user-images.githubusercontent.com/14175085/31314918-742e6c0e-ac0c-11e7-9ce4-dfedb4c8bbe6.png)

These are my settings:

![pic02](https://user-images.githubusercontent.com/14175085/31314919-7bbf8886-ac0c-11e7-8b18-488381478270.png)

And this is the plugin information screens:

![pic03](https://user-images.githubusercontent.com/14175085/31314922-81792ed0-ac0c-11e7-9f49-42ac783c7a52.png)

This only happens with filtered and NOT with unfiltered as unfiltered is unaffected and works properly.

Every build below angrylion's RDP Plus r4-52 seems to work like normal with filtered like angrylion's RDP Plus r4-34-dirty, angrylion's RDP Plus r4-8, angrylion's RDP Plus r3-85-dirty etc.

So it must be a recent commit that broke something.

**Comment by ata4** [comment]
I don't know where you got that build, but I bet it's the experimental deinterlacing build. The changes there were only temporary.

**Comment by SigmaVirus** [comment]
@ata4 
Thanks, does that mean this issue is solved already?

**Comment by ata4** [comment]
It wasn't really an issue to begin with, I created that effect deliberately to demonstrate it to theboy181. But I've checked it again and it still appears to be fine.

**Comment by SigmaVirus** [comment]
Hmm, so commit https://github.com/ata4/angrylion-rdp-plus/commit/5099be60ceb0059fae554e883a7f980f34bb3061 was just temporary changes?

I don't know what to make out of it but the shaking/wobbling is still happening at least in angrylion's RDP Plus r4-56 - https://github.com/ata4/angrylion-rdp-plus/commit/d4fce0e867ac28f783f41fb8e8afc7412767f970

**Comment by SigmaVirus** [comment]
angrylion's RDP Plus r4-65 - https://github.com/ata4/angrylion-rdp-plus/commit/d5e8ac5324d5bcece5dccd377b728ae520af7a64 still shows symptoms of shaking/wobbling Bombers Notebook when using Filtered output.

If you don't believe me then try this build out:
[angrylion-plus (17-10-10).zip](https://github.com/ata4/angrylion-rdp-plus/files/1374391/angrylion-plus.17-10-10.zip)

Thanks in advance!

**Comment by ata4** [comment]
The temporary change was to set `ctrl.serrate` always to zero, nothing else. I haven't even committed it. But it looks like you didn't use that build, since it's named "r4-56-dirty", not "r4-52".

Still, I cannot reproduce that problem. Neither with the PAL, nor the NTSC version. Not with overscan or without. Not with my recent build or the one you have linked. It's always perfectly stable.

**Comment by SigmaVirus** [comment]
Thanks for your feedback @ata4 I appreciate it!

I have now tried this with cxd4's RSP instead and it's still the same, basically the only thing I could do different with my current N64 setup if I'm not going to change emulator of course.

Here is a complete save file for Majora's Mask (Europe)
[ZELDA MAJORA'S MASK.zip](https://github.com/ata4/angrylion-rdp-plus/files/1378306/ZELDA.MAJORA.S.MASK.zip)

May it be useful to you!

**Comment by SigmaVirus** [comment]
As of **angrylion's RDP Plus r4-68** - https://github.com/ata4/angrylion-rdp-plus/commit/0cf1c82e9d2cf959e9e0f0025a56e484853cba7b the issue is still present using Filtered output.

**Comment by ata4** [comment]
Are you 100% sure you're actually *using* the most recent build and not just have it in your plugins folder? When comparing your screenshot with mine, it becomes obvious that your build has only half of the vertical interlaced resolution.

![mm](https://user-images.githubusercontent.com/1200105/31745663-00c36e30-b464-11e7-802b-8986f44a7223.gif)

This tells me you may still have that deinterlacing test build selected.

**Comment by SigmaVirus** [comment]
I think I'm 100% sure I got the most recent build there is as it contains https://github.com/ata4/angrylion-rdp-plus/commit/0cf1c82e9d2cf959e9e0f0025a56e484853cba7b - **Added overscan to the runtime config options.** which is the latest commit WE end-users see.

When you click on About in Project64 this is what it says:

```
angrylion's RDP Plus r4-68

Build commit:
master
0cf1c82e9d2cf959e9e0f0025a56e484853cba7b
2017-10-17 15:43:22 +0200

Build date: Oct 18 2017 22:03:52

https://github.com/ata4/angrylion-rdp-plus
```

Could you please attach your latest plugin? That way we can straight this out once and for all because this is driving me mad.

**Comment by ata4** [comment]
Okay, that helped me to narrow down the problem a bit. There's a variable called `emucontrolsvicurrent`, which apparently contains the flag whether the emulator controls `VI_V_CURRENT_LINE` correctly or not. My guess is that PJ64 1.7 doesn't control it and the workaround code does something unexpected. I was looking for a build of 1.7 before to debug it, but all I could find is some dubious looking third-party hosted links. I'll try it again with some precautions...

**Comment by ata4** [comment]
Finally found a working version, 1.7.0.50 (TheMejorDe64). Now I can reproduce that problem. 👍

And it looks like the problem is fixed by simply checking for `emucontrolsvicurrent` before adding the vertical offset. The lower vertical resolution can't be reliably fixed, though, only an upgrade to a newer PJ64 version that uses the interlacing registers correctly can do that.

**Comment by ata4** [comment]
Here's a test build:

[angrylion-plus.zip](https://github.com/ata4/angrylion-rdp-plus/files/1398291/angrylion-plus.zip)

**Comment by SigmaVirus** [comment]
@ata4 

I have just downloaded and tried out a Project64 2.4.0.9999 build from [here](http://hyvart.com/download/project64/ci/) and the shaking/wobbling doesn't occur there so tha's a good thing, will try out your test build now.

**Comment by SigmaVirus** [comment]
Well it looks like your build doesn't have the shaking/wobbling issue on either Project64 1.7 or 2.4 while my build did have shaking/wobbling on Project64 1.7 but not 2.4

As for the vertical interlaced resolution/deinterlacing thing it happens on both Project64 1.7 and 2.4 for me while your image looks perfect.

**Comment by SigmaVirus** [comment]
I think it's safe to close this now
