### ISSUE TITLE
Little regression in Perfect Dark game

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [ata4/angrylion-rdp-plus#49]
Commit 422b8dc425645db3768058bcb98768132e5a928c causes a regression in the intro of Perfect Dark, preventing the logo label from disappearing until the next scene.
![pd](https://user-images.githubusercontent.com/12230570/34285393-bac042d6-e696-11e7-9651-19953e134ae0.jpg)

**Comment by ata4** [comment]
Hm... I can confirm that the behavior is different to original Angrylion. However, I'm not completely sure which of the two is the "intended" behavior, since GLideN64 also does this. What's the hardware doing in this scenario?

**Comment by ata4** [comment]
Okay, I hope it's fixed now. The problem was that certain frames with a width of zero pixels were dropped entirely instead of rendering blank frames.

**Comment by SigmaVirus** [comment]
@Jj0YzL5nvJ 
Thanks for reporting this!

After playing with the before/after builds now and looking at the videos you provided I fully 100% understand what you meant by this and that it's not related to #51 

@ata4 
Wonderful commit, worked perfectly and flawlessly in Project64!
A big thank you!!!!

**Comment by Jj0YzL5nvJ** [comment]
Hmm... this does not fix to me, ironically now I can reproduce #51 and now I see more bugs ¬¬u
I will report later on appropriately.

**Comment by SigmaVirus** [comment]
@Jj0YzL5nvJ 
Have you tested it with Project64 with the latest build I have supplied in the #29 issue?

**Comment by Jj0YzL5nvJ** [comment]
I don't have a Windows installation at the moment, then no.

**Comment by SigmaVirus** [comment]
Well it is like @loganmc10 explained in #51, Project64 and Mupen64Plus handles Rare games differently so while the commit @ata4 made to fix this issue worked in Project64 it didn't work in m64p (Mupen64Plus)

Perfect Dark is very broken with this plugin in m64p (Mupen64Plus), especially with Unfiltered.
It haven't always been that way though since it worked quite well in November.

If you would try this with Project64 you would see that it works pretty much flawlessly.

**Comment by ata4** [comment]
Right... I was using glClear redundantly on Windows and on Linux, it was missing when the frames were blank. Both issues should hopefully be fixed now, for real this time.

**Comment by Jj0YzL5nvJ** [comment]
Yes, it's gone for good now.
