### ISSUE TITLE
Polygon issues with Mario Party games

### ISSUE THREAD

**Issue by BeeMovieScript** [ata4/angrylion-rdp-plus#76]
If you see a polygon really far, it will appear, and if you see that really close, it will disappear.

### **Mario Party**
![rdp plus issue 1](https://user-images.githubusercontent.com/28202371/46233683-f24d9600-c349-11e8-8dbd-b69ac37d4665.png)
![rdp plus issue 2](https://user-images.githubusercontent.com/28202371/46233684-f24d9600-c349-11e8-8e1e-f555f9b28610.png)

### **Mario Party 2**
![rdp plus issue 3](https://user-images.githubusercontent.com/28202371/46233705-0396a280-c34a-11e8-8fad-fc3b885e44bf.png)
![rdp plus issue 4](https://user-images.githubusercontent.com/28202371/46233706-042f3900-c34a-11e8-9a5e-8e2ccc26a8ed.png)

There are also polygon issues on Mario Party 3. I never took screenshots for this game.

**Comment by BeeMovieScript** [comment]
![rdp plus issue 5](https://user-images.githubusercontent.com/28202371/46265266-4481e900-c4fb-11e8-8023-3dc01822bdad.png)
This also occurs on Mario Party 3.

**Comment by ata4** [comment]
Are you using a WIP build? There was a bug in the Z-clipping code that has been fixed in the meantime, so I'd suggest either using r7 or the latest WIP build.

**Comment by BeeMovieScript** [comment]
I tried both, but the bug is still there, this is a major bug

**Comment by Jj0YzL5nvJ** [comment]
The last WIP build is two commits behind. I can update it tomorrow.

**Comment by BeeMovieScript** [comment]
ok but the next WIP build the issue will still occur, exclusively on first 3 mario parties

**Comment by Jj0YzL5nvJ** [comment]
A little late, but it's done.

**Comment by ata4** [comment]
Then I could use a save state of one of the example scenes, this could be a regression.

**Comment by ata4** [comment]
Hm... I can't reproduce this. This is my output of the first scene in MP1 using Project 64 2.4 and the latest master:

![marioparty_0002](https://user-images.githubusercontent.com/1200105/47847535-d36c7480-ddcb-11e8-927d-c639087d3614.png)

What emulator are you using?

**Comment by BeeMovieScript** [comment]
I used @LuigiBlood's latest 64DD.org build
https://64dd.org/downloads.html
